// Local Host
### Get all contacts
GET http://localhost:3000/users 


####User contat by id 


GET http://localhost:3000/users/67803dfcc31f58d7dc2161c8


### POST - create contact
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "firstName": "Jhon", "lastName": "Tailor", "email": "Jtailor123@gmail.com", "favoriteColor": "purple", "birthday": "09-15-1999"
}
### PUT - update contact
PUT http://localhost:3000/users/6786c0faa8840b394de35012 HTTP/1.1
content-type: application/json

{
    "firstName": "Jhon", "lastName": "Tailor", "email": "Jtailor123@gmail.com", "favoriteColor": "purple", "birthday": "09-15-1999"
}
### DELETE contact
DELETE http://localhost:3000/users/6786c0faa8840b394de35012 HTTP/1.1




// REnder 
### Get all contacts
GET https://cse-341-project1-kiy0.onrender.com/users 


### POST - create contact
POST https://cse-341-project1-kiy0.onrender.com/users HTTP/1.1
content-type: application/json

{
    "firstName": "Maria", "lastName": "SAnchez", "email": "MSanchez@gmail.com", "favoriteColor": "pink", "birthday": "09-15-2000"
}
### PUT - update contact
PUT https://cse-341-project1-kiy0.onrender.com/users/6786c1c476c009e242cbf396 HTTP/1.1
content-type: application/json

{
    "firstName": "Maria", "lastName": "SAnchez", "email": "MSanchez@gmail.com", "favoriteColor": "pink", "birthday": "09-15-2000"
}
### DELETE contact
DELETE https://cse-341-project1-kiy0.onrender.com/users/6786c1a876c009e242cbf395 HTTP/1.1
